Adicionando validators e consulta pedidos cozinha
AdrianoVitoriano/PI-Pastelaria-2024-01 pull request #16
Opened 2024-05-19 17:03 UTC by DiegoS-Nunes

2024-05-20 14:10 UTC, AdrianoVitoriano requested changes
# Necessário modificações.

Foram feitos comentarios em 13 arquivos solicitando alteração pequenas e/ou grandes, por favor verificar e alterar.

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/Controller/comandas.controller.js
# Regras de negócios 

Acredito que não faça sentido continuarmos com uma rota para criar uma comanda nova, pois a comanda sempre tem que ter um pedido atribuido, ou seja, só criar uma nova comanda se criarmos um novo pedido e não houver nenhuma comanda em aberto. Assim acredito que não faz mais sentido uma rota de postComanda que eu acabei criando lá trás.

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/Controller/itens.controller.js
# req.body.id = req.params.id

Para que a rota de PUT e DELETE funcione, é necessário que seja passado no corpo da requisição o id. Como a nesse PR foi alterado a forma de receber o id nas Rotas de PUT, DELETE e GET (GetById), é necessário que atribua ao corpo da requisição o id que foi passado no parâmetro utilizando a atribuição abaixo:

```Javascript
static async putItem(req, res) {
  const errors = validationResult(req)
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() })
  }
  
  req.body.id = req.params.id // atribuindo o id que está no parâmetro ao body.
  
  res.json(await updateById(req.body, Itens));
  }
```

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/Controller/itensPedidos.controller.js
# req.body.id = req.params.id

Para que a rota de GET (GetById) funcione, é necessário que atribua ao corpo da requisição o id que foi passado no parâmetro utilizando a atribuição abaixo:

```Javascript
getItensPedidosById(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }
    req.body.id = req.params.id // atribuindo o id que está no parâmetro ao body
    res.json(await getById(req.body, ItensPedidos));
  }
```

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/Controller/mesas.controller.js
# deleteMesa(req, res) {...}

Alterar a linha do res de `res.json(await deleteById(req.params, Mesas))` para `es.json(await deleteById(req.body, Mesas))`.

```Javascript

  static async deleteMesa(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = req.params.id

    res.json(await deleteById(req.body, Mesas)); // res.json(await deleteById(req.params, Mesas));
  }
}

```

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/Controller/pedidos.controller.js
# Alterações necessárias

## req.body.id = req.params.id

Para que a rota de PUT e DELETE funcione, é necessário que seja passado no corpo da requisição o id. Como a nesse PR foi alterado a forma de receber o id nas Rotas de PUT, DELETE e GET (GetById), é necessário que atribua ao corpo da requisição o id que foi passado no parâmetro utilizando a atribuição abaixo:

```Javascript

  static async putPedido(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }
    req.body.id = req.params.id // atribuindo o id que está no parâmetro ao body.
    res.json(await updateById(req.body, Pedidos));
  }

```

## Retirar console.log()

Retirar console.log() da função validarRequisição(), igual a função abaixo:

```Javascript

async function validarRequisição(body) {
  return (await validarMesa(body.idMesa) && await validarUsuario(body.idUsuario) && ((body.itens)?((body.itens[0])?true:false):false))?{result:true}:{result:false}
}

```

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/Controller/tipoItens.controller.js
# Alterações necessárias

## req.body.id = req.params.id

Para que a rota de PUT e DELETE funcione, é necessário que seja passado no corpo da requisição o id. Como a nesse PR foi alterado a forma de receber o id nas Rotas de PUT, DELETE e GET (GetById), é necessário que atribua ao corpo da requisição o id que foi passado no parâmetro utilizando a atribuição abaixo:

```Javascript

    static async putTipoItens(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }
    req.body.id = req.params.id // atribuindo o id que está no parâmetro ao body.
    res.json(await updateById(req.body, TipoItens));
  }
```

## Alterar Res do GetById

Alterar a resposta para pegar o ID do parâmetro, pois as rotas do GetById recebe o id pelo parâmetro na URL

```Javascript
  static async getTipoItensById(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }
    res.json(await getById(req.params, TipoItens)); // res.json(await getById(req.body, TipoItens));
}
```

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/Controller/usuarios.controller.js
# Alterações necessárias

## req.body.id = req.params.id

Para que a rota de PUT e DELETE funcione, é necessário que seja passado no corpo da requisição o id. Como a nesse PR foi alterado a forma de receber o id nas Rotas de PUT, DELETE e GET (GetById), é necessário que atribua ao corpo da requisição o id que foi passado no parâmetro utilizando a atribuição abaixo:

```Javascript
  static async putUsuario(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }
    req.body.id = req.params.id // atribuindo o id que está no parâmetro ao body.
    res.json(await updateById(req.body, Usuarios));
  }
```

## Alterar Res do GetById

Alterar a resposta para pegar o ID do parâmetro, pois as rotas do GetById recebe o id pelo parâmetro na URL

```Javascript
  static async getUsuarioById(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }
    res.json(await getById(req.params, TipoItens)); // res.json(await getById(req.body, TipoItens));
}
```

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/crud.js
# Alterações necessárias

## Descartar alteração na função `updateById(body,table){...}`

- Foi alterado o nome da variável `body` para req, mas como essa função sempre vai receber o `req.body`, não faria muito sentido ficar usando o nome req, pois sempre vamos receber o body.
- Na linha 60 `.update(req.id, req.abertabody)` foi passado a propriedade `.abertabody`, que não existe.

Retornar a função como está abaixo:

```Javascript
export async function updateById(body, table) {
  if (existeId(body.id)) {
    try {
      await dataBase
        .getRepository(table.options.name)
        .update(body.id, body)
        .catch((err) => {
          return err;
        });
      return { result: true, id: body.id };
    } catch (err) {
      return err;
    }
  } else {
    return err400;
  }
}
```
## Descartar alteração na função `deleteById(body,table){...}`

- Foi alterado o nome da variável `body` para req, mas como essa função sempre vai receber o `req.body`, não faria muito sentido ficar usando o nome req, pois sempre vamos receber o body.

Retornar a função como está abaixo:

```Javascript
export async function deleteById(body, table) {
  if (existeId(body.id)) {
    try {
      await dataBase
        .getRepository(table.options.name)
        .delete(body.id)
        .catch((err) => {
          return err;
        });
      return { result: true, id: body.id };
    } catch (err) {
      return err;
    }
  } else {
    return err400;
  }
}
```

## Descartar alteração na função `conferirComanda(body,table){...}`

- Foi alterado o nome da variável `body` para req, mas como essa função sempre vai receber o `req.body`, não faria muito sentido ficar usando o nome req, pois sempre vamos receber o body.

Retornar a função como está abaixo:

```Javascript
export async function conferirComanda(body, table) {
  if (existeId(body.idMesa)) {
    try {
      const res = await dataBase
        .getRepository(table.options.name)
        .find({ where: { idMesa: body.idMesa, aberta: 1 } })
        .catch((err) => {
          return err;
        });
      if (res[0]) {
        return { result: true, id: res[0].id, total: res[0].total };
      } else {
        return { result: false };
      }
    } catch (err) {
      return err;
    }
  } else {
    return err400;
  }
}
```

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/validator/comandas.validator.js
# CreatecomandasValidator()

Como comentado no arquivo comandas.controller.js, não se faz mais necessario uma rota para criar uma comanda sem pedido. Esse validator não se fará necessário.

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/validator/pedidos.validator.js
# Alterações necessárias

## createPedidosValidator()

- A validação body('id').isInt().withMessage("id inválido"), irá impedir o cadastro de qualquer pedido, pois quando se cadastra alguma coisa, não se tem o id, você espera receber o id de volta, pois o id é um campo de autoincremento do banco de dados, ou seja, o banco quem cria o id.

Para criar um pedido, são necessárias as propriedades abaixo:

- idUsuario (INT);
- idMesa (INT);
- itens (ARRAY);

O restante das propriedades são atribuidas automaticamente pela função postPedidos.

## updatePedidosValidator()

A comanda do pedido não pode ser modificada.

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/validator/usuarios.validator.js
# createUsuariosValidator

1. A validação `body('id').isInt().withMessage("id inválido")`, irá impedir o cadastro de qualquer usuário, pois quando se cadastra alguma coisa, não se tem o id, você espera receber o id de volta, pois o id é um campo de autoincremento do banco de dados, ou seja, o banco quem cria o id.
1. A senha e email, são valores do tipo String, não Int.

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/validator/itens.validator.js
# createItensValidator

1. A validação `body('id').isInt().withMessage("id inválido")`, irá impedir o cadastro de qualquer item, pois quando se cadastra alguma coisa, não se tem o id, você espera receber o id de volta, pois o id é um campo de autoincremento do banco de dados, ou seja, o banco quem cria o id.

2024-05-20 14:10 UTC, AdrianoVitoriano commented on src/routes.js
# Excluir rota de criação de comandas.

Conforme já comentado em outros reviews, excluir a rota de criação de comandas.

2024-05-23 22:50 UTC, DiegoS-Nunes commented on src/Controller/comandas.controller.js
Excluído a rota

2024-05-23 22:59 UTC, DiegoS-Nunes commented on src/validator/comandas.validator.js
Excluído

2024-05-23 23:01 UTC, DiegoS-Nunes commented on src/validator/pedidos.validator.js
Não tem uma coluna de itens na tabela de pedidos.

2024-05-23 23:21 UTC, DiegoS-Nunes commented on src/Controller/itens.controller.js
```js
  static async putItem(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = req.params.id

    res.json(await updateById(req.body, Itens));
  }
  static async deleteItem(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = req.params.id

    res.json(await deleteById(req.body, Itens));
  }

2024-05-23 23:22 UTC, DiegoS-Nunes commented on src/Controller/itensPedidos.controller.js
```js
class ItensPedidosController {
  static async getAllItensPedidos(req, res) {
    res.json(await getAll(ItensPedidos));
  }
  static async getItensPedidosById(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = req.params.id
    
    res.json(await getById(req.body, ItensPedidos));
  }
}
export async function inserirItens(itens,idPedido){
  const itensPreco = await getPrecos(itens.map((item) => item.idItem))
  let total = 0
  itens.forEach((objeto) => {
    objeto.subtotal = objeto.quantidade * itensPreco.find((item) => item.itens_id == objeto.idItem).itens_preco;
    objeto.idPedido = idPedido;
    total += objeto.subtotal
  });
  await insert(itens, ItensPedidos)
  return total
}

2024-05-23 23:23 UTC, DiegoS-Nunes commented on src/Controller/mesas.controller.js
```js
  static async putMesa(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }
    
    req.body.id=req.params.id

    res.json(await updateById(req.body, Mesas));
  }
  static async deleteMesa(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = req.params.id

    res.json(await deleteById(req.body, Mesas));
  }

2024-05-23 23:24 UTC, DiegoS-Nunes commented on src/Controller/pedidos.controller.js
```js
static async putPedido(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = req.params.id
    
    res.json(await updateById(req.body, Pedidos));
  }

  static async deletePedido(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = req.params.id

    res.json(await deleteById(req.params, Pedidos));
  }
```

```js
async function validarRequisição(body) {
  return (await validarMesa(body.idMesa) && await validarUsuario(body.idUsuario) && ((body.itens)?((body.itens[0])?true:false):false))?{result:true}:{result:false}
}
```

2024-05-23 23:25 UTC, DiegoS-Nunes commented on src/Controller/tipoItens.controller.js
```js
class TipoItensController {
  static async getAllTipoItens(req, res) {
    res.json( await getAll(TipoItens));
  }
  static async getTipoItensById(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }
  
    res.json(await getById(req.params, TipoItens)); // res.json(await getById(req.body, TipoItens));
  
  }
  static async postTipoItens(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    res.json(await insert(req.body, TipoItens));
  }
  static async putTipoItens(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }
    
    req.body.id = req.params.id

    res.json(await updateById(req.body, TipoItens));
  }
  static async deleteTipoItens(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = req.params.id

    res.json(await deleteById(req.body, TipoItens));
  }
}

2024-05-23 23:25 UTC, DiegoS-Nunes commented on src/Controller/usuarios.controller.js
```js
class UsuarioController {
  static async getAllUsuarios(req, res) {
    res.json(await getAll(Usuarios));
  }
  static async getUsuarioById(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }
  
    res.json(await getById(req.params, TipoItens));
  }
  static async postUsuario(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    res.json(await insert(req.body, Usuarios));
  }
  static async putUsuario(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = req.params.id

    res.json(await updateById(req.body, Usuarios));
  }
  static async deleteUsuario(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = req.params.id

    res.json(await deleteById(req.body, Usuarios));
  }
}

2024-05-23 23:27 UTC, DiegoS-Nunes commented on src/crud.js
```js
export async function updateById(body, table) {
  if (existeId(body.id)) {
    try {
      await dataBase
        .getRepository(table.options.name)
        .update(body.id, body)
        .catch((err) => {
          return err;
        });
      return { result: true, id: body.id };
    } catch (err) {
      return err;
    }
  } else {
    return err400;
  }
}
```

```js
export async function deleteById(body, table) {
  if (existeId(body.id)) {
    try {
      await dataBase
        .getRepository(table.options.name)
        .delete(body.id)
        .catch((err) => {
          return err;
        });
      return { result: true, id: body.id };
    } catch (err) {
      return err;
    }
  } else {
    return err400;
  }
}
```

```js
export async function conferirComanda(body, table) {
  if (existeId(body.idMesa)) {
    try {
      const res = await dataBase
        .getRepository(table.options.name)
        .find({ where: { idMesa: body.idMesa, aberta: 1 } })
        .catch((err) => {
          return err;
        });
      if (res[0]) {
        return { result: true, id: res[0].id, total: res[0].total };
      } else {
        return { result: false };
      }
    } catch (err) {
      return err;
    }
  } else {
    return err400;
  }
```

2024-05-23 23:30 UTC, DiegoS-Nunes commented on src/validator/usuarios.validator.js
```js
import { body, param } from 'express-validator'

export const idUsuariosValidator = [
    param('id').isInt().withMessage("id inválido"),
]

export const createUsuariosValidator = [
    body('nome').isString().withMessage("nome inválido"),
    body('cargo').isString().withMessage("cargo inválido"),
    body('email').isEmail().withMessage("email inválido"),
    body('cpf').isInt().withMessage("cpf inválido"),
    body('senha').isString().withMessage("senha inválido"),
]

export const updateUsuariosValidator = [
    body('nome').optional().isString().withMessage("nome inválido"),
    body('cargo').optional().isString().withMessage("cargo inválido"),
    body('email').optional().isEmail().withMessage("email inválido"),
    body('cpf').optional().isInt().withMessage("cpf inválido"),
    body('senha').optional().isString().withMessage("senha inválido"),
]

2024-05-23 23:30 UTC, DiegoS-Nunes commented on src/validator/itens.validator.js
```js
import { body, param } from 'express-validator'

export const idItensValidator = [
    param('id').isInt().withMessage("id inválido"),
]

export const createItensValidator = [
    body('nome').isString().withMessage("Nome inválido"),
    body('preco').isFloat().withMessage("Preco inválido"),
    body('idTipo').isInt().withMessage("idTipo inválido"),
]

export const updateItensValidator = [
    body('nome').optional().isString().withMessage("Nome inválido"),
    body('preco').optional().isFloat().withMessage("Preco inválido"),
    body('idTipo').optional().isInt().withMessage("idTipo inválido"),

2024-05-23 23:31 UTC, DiegoS-Nunes commented on src/routes.js
Excluído.

2024-05-24 00:12 UTC, AdrianoVitoriano commented on src/validator/pedidos.validator.js
Realmente não tem um campo de itens na tabela pedido, pois não são armazenados nessa tabela e sim na tabela itensPedidos, e como estamos criando um novo pedido, precisamos dos itens sendo passados nessa requisição.

2024-05-24 00:40 UTC, DiegoS-Nunes commented
##cozinhas.controller

Criação do arquivo cozinhas.controller.js para uso futuro:

´´´js
import { body, param } from 'express-validator'

export const idCozinhasValidator = [
  param('id').isInt().withMessage("id inválido"),
]

export const updateCozinhasValidator = [
  body('produzido').isInt().withMessage("Status Aberta inválido"),
]
```

Criação das rotas de consulta da tabela cozinha linhas 75,76:

```js
//router.get("/cozinha", cozinhasController.getAllCozinhas); // Rota que retorna todos os itens da cozinha.
//router.get("/cozinha/:id", cozinhasController.getCozinhasById); // Rota que retorna os itens da cozinha pelo id.
```

2024-05-25 23:47 UTC, DiegoS-Nunes commented
## Parseando id do Params

Todas as funções DELETE e PUT de todos os Controllers tiveram os id's do parâmetro parseados para int antes de serem atribuídos ao body. Pois o id do params é uma string e o id **deve** ser um int.

```js
req.body.id = parseInt(req.params.id)
```

## PRAGMA foreign_keys Crud.js

A operação de delete não estava funcionando pois o sqlite não deixa excluir um item que está sendo referenciado em outra tabela como chave estrangeira. Para corrigir isso foi adicionado um comando antes da operação de delete:

```
PRAGMA foreign_keys = OFF
```
```
PRAGMA foreign_keys = ON
```

Esse comando desativa todas as chaves estrangeiras possibilitando a exclusão e logo após ele ativa novamente. Dessa forma ele não deleta todos os itens na tabela que contenha a chave estrangeira referenciada, como faz o método ON CASCADE.

```js
export async function deleteById(body, table) {
  if (existeId(body.id)) {
    try {

      await dataBase.query(`PRAGMA foreign_keys = OFF`);

      await dataBase
        .getRepository(table.options.name)
        .delete(body.id)
        .catch((err) => {
          return err;
        });

      await dataBase.query(`PRAGMA foreign_keys = ON`);
      return { result: true, id: body.id };
    } catch (err) {
      return err;
    }
  } else {
    return err400;
  }
}
```

2024-05-26 12:49 UTC, AdrianoVitoriano commented on src/validator/pedidos.validator.js
Altere assim:

```Javascript
export const createPedidosValidator = [
    body('idMesa').isInt().withMessage("idMesa inválido"),
    body('idUsuario').isInt().withMessage("idUsuario inválido"),
    body('itens').isArray().withMessage("itens inválido"),
]
```

2024-05-26 12:54 UTC, AdrianoVitoriano commented on src/validator/usuarios.validator.js
updateUsuariosValidator está errado... Tente achar o erro

2024-05-26 12:56 UTC, AdrianoVitoriano commented on src/Controller/pedidos.controller.js
Ache o erro...

```Javascript

  static async putPedido(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = parseInt(req.params.id)
    
    res.json(await updateById(req.params.id, Pedidos));
  }

```

2024-05-26 13:01 UTC, AdrianoVitoriano commented on src/routes.js
A rota e a função continuam lá...

2024-05-26 14:19 UTC, DiegoS-Nunes commented on src/Controller/tipoItens.controller.js
Corrigido:

```js
  static async putPedido(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = parseInt(req.params.id)
    
    res.json(await updateById(req.body, Pedidos));
  }

  static async deletePedido(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = parseInt(req.params.id)

    res.json(await deleteById(req.body, Pedidos));
  }

2024-05-26 14:20 UTC, DiegoS-Nunes commented on src/Controller/pedidos.controller.js
Corrigido:

```js
  static async putPedido(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = parseInt(req.params.id)
    
    res.json(await updateById(req.body, Pedidos));
  }

  static async deletePedido(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = parseInt(req.params.id)

    res.json(await deleteById(req.body, Pedidos));
  }

2024-05-26 14:27 UTC, DiegoS-Nunes commented on src/validator/usuarios.validator.js
Cargo corrijido para int

```js
export const createUsuariosValidator = [
    body('nome').isString().withMessage("nome inválido"),
    body('cargo').isInt().withMessage("cargo inválido"),
    body('email').isEmail().withMessage("email inválido"),
    body('cpf').isInt().withMessage("cpf inválido"),
    body('senha').isString().withMessage("senha inválido"),
]

export const updateUsuariosValidator = [
    body('nome').optional().isString().withMessage("nome inválido"),
    body('cargo').optional().isInt().withMessage("cargo inválido"),
    body('email').optional().isEmail().withMessage("email inválido"),
    body('cpf').optional().isInt().withMessage("cpf inválido"),
    body('senha').optional().isString().withMessage("senha inválido"),
]

2024-05-26 14:32 UTC, DiegoS-Nunes commented on src/routes.js
A rota de criação não está, só as outras:

```js
// Rotas da tabela comandas

router.get("/comandas", ComandasController.getAllComandas); // Rota que retorna todas as comandas.
router.put("/comandas/:id", [idComandasValidator, updateComandasValidator], ComandasController.putComanda); // Rota que atualiza a comanda no banco pelo id.
router.delete("/comandas/:id", idComandasValidator, ComandasController.deleteComanda); // Rota que deleta a comanda do banco pelo id.
router.get("/comandas/:id", idComandasValidator, ComandasController.getComandaById); //  Rota que retorna uma comanda pelo id.
```

Nos validators também:
```js
import { body, param } from 'express-validator'

export const idComandasValidator = [
  param('id').isInt().withMessage("id inválido"),
]

export const updateComandasValidator = [
  body('total').optional().isFloat().withMessage("Total inválido"),
  body('mesasId').optional().isInt().withMessage("mesasId inválido"),
  body('abertura').optional().isString().withMessage("Abertura inválida"),
  body('aberta').optional().isInt().withMessage("Status Aberta inválido"),
]
```

No controller também:

```js
class ComandasController {
  static async getAllComandas(req, res) {

    res.json(await getAll(Comandas));
  }
  static async getComandaById(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    res.json(await getById(req.params, Comandas));
  }
  static async putComanda(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = parseInt(req.params.id)

    res.json(await conferirComandaExecutar(req, updateById));
  }
  static async deleteComanda(req, res) {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() })
    }

    req.body.id = parseInt(req.params.id)

    res.json(await conferirComandaExecutar(req, deleteById));
  }
}
```

2024-05-26 14:35 UTC, DiegoS-Nunes commented
Exclusão da consulta cozinha

```js
import { Query } from "typeorm/driver/Query.js";
import { dataBase } from "./ormconfig.js";
import { In } from "typeorm";

const err400 = {
  statusCode: 400,
  msg: "ID não foi encontrado nos parâmetros passados. Por gentileza verificar a variável passada e/ou a documentação.",
};

export async function getAll(table) {
  return await dataBase.getRepository(table.options.name).find();
}
export async function getById(req, table) {
  if (existeId(req.id)) {
    const res = await dataBase
      .getRepository(table.options.name)
      .find({ where: { id: req.id } })
      .catch((err) => {
        return err;
      });

    if (res[0]) {
      res.result = true;
      return res;
    } else {
      return { result: false };
    }
  } else {
    return err400;
  }
}
export async function getSomeById(arrayId, table, arrayColumnsReturn) {
  if (existeId(arrayId[0])) {
    return await dataBase
      .getRepository(table.options.name)
      .createQueryBuilder(table.options.name)
      .select(arrayColumnsReturn)
      .where({ id: In(arrayId) })
      .getRawMany();
  } else {
    return err400;
  }
}

export async function insert(body, table) {
  const res = await dataBase
    .getRepository(table.options.name)
    .save(body)
    .catch((err) => {
      return err;
    });
  return { result: true, id: res.id };
}

export async function updateById(body, table) {
  if (existeId(body.id)) {
    try {
      await dataBase
        .getRepository(table.options.name)
        .update(body.id, body)
        .catch((err) => {
          return err;
        });
      return { result: true, id: body.id };
    } catch (err) {
      return err;
    }
  } else {
    return err400;
  }
}

export async function deleteById(body, table) {
  if (existeId(body.id)) {
    try {

      await dataBase.query(`PRAGMA foreign_keys = OFF`);

      await dataBase
        .getRepository(table.options.name)
        .delete(body.id)
        .catch((err) => {
          return err;
        });

      await dataBase.query(`PRAGMA foreign_keys = ON`);
      return { result: true, id: body.id };
    } catch (err) {
      return err;
    }
  } else {
    return err400;
  }
}

export async function conferirComanda(body, table) {
  if (existeId(body.idMesa)) {
    try {
      const res = await dataBase
        .getRepository(table.options.name)
        .find({ where: { idMesa: body.idMesa, aberta: 1 } })
        .catch((err) => {
          return err;
        });
      if (res[0]) {
        return { result: true, id: res[0].id, total: res[0].total };
      } else {
        return { result: false };
      }
    } catch (err) {
      return err;
    }
  } else {
    return err400;
  }
}

export function dataHora() {
  const date = new Date();
  return `${date.getDate()}/${
    date.getMonth() + 1
  }/${date.getFullYear()} | ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`;
}
function existeId(id) {
  return id === undefined ? false : true;
}

export async function totalPorUsuario() {
   
  try {
    const result = await dataBase.query(`
      SELECT 
        p.Id AS Pedido_Id,
        u.nome AS Nome_Usuário,
        SUM(p.total) as Total
      FROM
        pedidos p
      INNER JOIN 
        usuarios u on p.idUsuario = u.id
      GROUP BY
        u.id
    `);

    return result;    
  } catch (error) {
    console.error("Erro ao obter relatório de vendas:", error);
    return null;
  }
}

export async function totalPorMesa() {
  try {
    const query = `
    SELECT
      m.id AS Nº_Mesa,
      m.localizacao AS Localização_Mesa,
      SUM(c.total) as Total
    FROM
      comandas c
    INNER JOIN 
      mesas m on c.idMesa = m.id
    GROUP BY
      m.id
    `;

    const result = await dataBase.query(query);

    return result;
  } catch (error) {
    console.error("Erro ao obter relatório de vendas:", error);
    return null;
  }
}
/* EXCLUIDO
export async function cozinha() {
  try {
    const query = `
    SELECT
      ip.pedidosId AS Pedido_ID,
      ip.quantidade AS Pedido_Quantidade,
      i.nome as Item,
      c.mesasId as Nº_Mesa
    FROM
      itensPedidos ip
      INNER JOIN 
        pedidos p on ip.pedidosId = p.id
      INNER JOIN 
        comandas c on p.comandasId = c.id
      INNER JOIN
        itens i on ip.itensId = i.id
    WHERE
      cozinha = 1
    GROUP BY
      ip.Id
    `;

    const result = await dataBase.query(query);

    return result;
  } catch (error) {
    console.error("Erro ao obter relatório de vendas:", error);
    return null;
  }
}

2024-05-26 23:45 UTC, AdrianoVitoriano approved these changes

2024-05-26 23:47 UTC, merged